# nonk8s
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero-networkpolicies
  namespace: bigbang
spec:
  targetNamespace: velero
  releaseName: velero-networkpolicies
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
  values:
    resources:
      - apiVersion: "networking.k8s.io/v1"
        kind: NetworkPolicy
        metadata:
          name: allow-from-velero-minio
        spec:
          ingress:
            - ports:
                - port: 8085
                  protocol: TCP
              from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: velero-minio
          podSelector: {}
          policyTypes:
            - Ingress
      - apiVersion: "networking.k8s.io/v1"
        kind: NetworkPolicy
        metadata:
          name: allow-to-velero-minio
        spec:
          egress:
            - ports:
                - port: 80
                  protocol: TCP
                - port: 9000
                  protocol: TCP
                - port: 9090
                  protocol: TCP
              to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: velero-minio
          podSelector: {}
          policyTypes:
            - Egress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero-minio-networkpolicies
  namespace: bigbang
spec:
  targetNamespace: velero-minio
  releaseName: velero-minio-networkpolicies
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: charts/raw
      sourceRef:
        kind: GitRepository
        name: zarf-package-software-factory
        namespace: flux-system
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  dependsOn:
    - name: bigbang
      namespace: bigbang
  values:
    resources:
      - apiVersion: "networking.k8s.io/v1"
        kind: NetworkPolicy
        metadata:
          name: allow-from-velero
        spec:
          ingress:
            - ports:
                - port: 80
                  protocol: TCP
                - port: 9000
                  protocol: TCP
                - port: 9090
                  protocol: TCP
              from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: velero
          podSelector: {}
          policyTypes:
            - Ingress
      - apiVersion: "networking.k8s.io/v1"
        kind: NetworkPolicy
        metadata:
          name: allow-to-velero
        spec:
          egress:
            - ports:
                - port: 8085
                  protocol: TCP
              to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: velero
          podSelector: {}
          policyTypes:
            - Egress
